# Config file for the labeler Github Action
# https://hub.docker.com/r/jimschubert/labeler-action
# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true

# comments object allows you to specify a different message for issues and prs

# comments:
#   issues: |
#     Thanks for opening this issue!
#     I have applied any labels matching special text in your title and description.

#     Please review the labels and make any necessary changes.
#   prs: |
#     Thanks for the contribution!
#     I have applied any labels matching special text in your title and description.

#     Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
labels:
  'bug':
    include:
      - '/^bug(\\(.*\\))?:/i'
    exclude: []
  'feat':
    include:
      - '/^feat(\\(.*\\))?:/i'
    exclude: []
  'fix':
    include:
      - '/^fix(\\(.*\\))?:/i'
    exclude: []
  'build':
    include:
      - '/^build(\\(.*\\))?:/i'
    exclude: []
  'docs':
    include:
      - '/^docs(\\(.*\\))?:/i'
    exclude: []
  'style':
    include:
      - '/^style(\\(.*\\))?:/i'
    exclude: []
  'test':
    include:
      - '/^test(\\(.*\\))?:/i'
    exclude: []
  'chore':
    include:
      - '/^chore(\\(.*\\))?:/i'
    exclude: []
  'ci':
    include:
      - '/^ci(\\(.*\\))?:/i'
    exclude: []
  'perf':
    include:
      - '/^perf(\\(.*\\))?:/i'
    exclude: []
  'revert':
    include:
      - '/^revert(\\(.*\\))?:/i'
    exclude: []