name: Publish to Pypi

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        python -m twine upload dist/* --repository-url https://upload.pypi.org/legacy/ -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
